### ISSUE TITLE
¿Cargos a Tarjeta, Banco y Tienda?

### ISSUE THREAD

**Issue by eliacimdavila** [open-pay/openpay-js#11]
Hola, buenas tardes.

Quisiera saber, una vez que ya tengo generado el Token, ¿cómo aplico el cargo a la tarjeta? A su vez, ¿cómo sería en el caso de pagar con transferencia a banco o en Tienda? Quizás éste no es el sitio adecuado para esto, ya que no es en sí un issue, sino más bien unas dudas. Si es así, les agradecería me indicaran el lugar y forma adecuado para resolverlas. 

Muchas gracias.

**Comment by ecarloslr** [comment]
Hola, una vez que ya cuentes con el Token, tienes que hacer una petición desde tu servidor al servicio de cargos de Openpay. Puedes encontrar un ejemplo corto aquí: 
http://www.openpay.mx/docs/card-charge.html
Para más detalles puedes consultar la documentación de la API: 
http://www.openpay.mx/docs/api/#con-id-de-tarjeta-o-token

Para los cargos en tienda o en banco no es necesario el token. Puedes ver el flujo de esos dos tipos de cargo aquí:
http://www.openpay.mx/docs/store-charge.html
http://www.openpay.mx/docs/bank-charge.html

También puedes ver un ejemplo de una implementación muy básica de los métodos de pago en este proyecto de Github:
https://github.com/open-pay/openpay-shopping-sample

**Comment by DeniseCigarroa** [comment]
Hola buen día, ¿donde localizo el id del objeto transacción regresado al crearse el cargo?
