### ISSUE TITLE
Validar si una tarjeta es de Débito o Crédito

### ISSUE THREAD

**Issue by fr20587** [open-pay/openpay-js#25]
Buenas necesito saber si la librería tiene algún método para validar si una tarjeta es de **Crédito** o **Débito**.

Muchas gracias por los comentarios.

**Comment by MonicaPArroyo** [comment]
Lo que yo estoy tratando de implementar y que parece va a funcionar es primero guardar la tarjeta y en el objeto que devuelve indica el "type" de ésta. Si resulta ser de crédito, muestro un mensaje de error al usuario y hago otra petición a Openpay para que borre la tarjeta. De esa forma no permito que el usuario haga movimientos con una tarjeta de crédito. Si es un caso en el que se quiere hacer el cargo al momento de registrar los datos, entonces no se me ocurre una forma para hacerlo

**Comment by fr20587** [comment]
> Lo que yo estoy tratando de implementar y que parece va a funcionar es primero guardar la tarjeta y en el objeto que devuelve indica el "type" de ésta. Si resulta ser de crédito, muestro un mensaje de error al usuario y hago otra petición a Openpay para que borre la tarjeta. De esa forma no permito que el usuario haga movimientos con una tarjeta de crédito. Si es un caso en el que se quiere hacer el cargo al momento de registrar los datos, entonces no se me ocurre una forma para hacerlo

Interesante solución en mi caso no hago guardo la tarjeta solo hago un cargo directo, pero lo tendré en cuenta. 👍

**Comment by MonicaPArroyo** [comment]
[Documentación](https://documents.openpay.mx/docs/api/#confirmar-un-cargo)
Creo que hay una forma para lo que necesitas, pero sólo haciendo pruebas podrías comprobarlo. Con lo de confirmar un cargo, parece que devuelve el tipo, y si el tipo es de crédito, pues ya no se hace el segundo llamado que es el que confirmaría que se realice el cargo

**Comment by fr20587** [comment]
> [Documentación](https://documents.openpay.mx/docs/api/#confirmar-un-cargo) Creo que hay una forma para lo que necesitas, pero sólo haciendo pruebas podrías comprobarlo. Con lo de confirmar un cargo, parece que devuelve el tipo, y si el tipo es de crédito, pues ya no se hace el segundo llamado que es el que confirmaría que se realice el cargo

Muchas gracias por la información, utilizaré esta vía 👍
