### ISSUE TITLE
Mensajes de error

### ISSUE THREAD

**Issue by adriancuadros** [open-pay/openpay-js#3]
Hola,

Creo que este es un potencial issue: https://github.com/open-pay/openpay-js/blob/master/lib/openpay.v1.js#L191-L194

Esto porque si el callback falla por cualquier motivo parece que el error estuvo de su lado. Considero que el try no debería involucrar el éxito o error del callback. Me pasé un rato viendo porque era el error y encontré que era mío. 

Saludos

**Comment by darkaz** [comment]
Lo revisamos Adrian. Gracias por el reporte.

**Comment by EdgarVaguencia** [comment]
Coincido con @adriancuadros estuve realizando algunas pruebas y obtenía el error "Response error (Unknown final status)" a pesar que en el logs de sandbox se había creado correctamente. 

Mi problema era que lo estaba integrando dentro de backbone y al hacer el callback de la función success dejaba fuera de scope mi toda mi vista. Al final lo resolví con una simple función anónima.

Pero si deberían considerar sacar del try la llamada a la función callback y simplemente realizar la llamada en caso de tener el status 200 ó 201.

Saludos.
