### ISSUE TITLE
Bug en Openpay.card.validateExpiry()

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [open-pay/openpay-js#4]
La validación de las fechas de expiración de las tarjetas no es precisamente exacta:

![screen shot 2015-11-27 at 5 13 07 pm](https://cloud.githubusercontent.com/assets/5341310/11448933/32f691b2-952a-11e5-991e-8daf58da9099.png)

**Comment by marcosAlvarado** [comment]
Listo!
Saludos!

2015-11-27 17:14 GMT-06:00 Miguel Angel Velazco <notifications@github.com>:
