### ISSUE TITLE
Envio de parametro -u CURL en un HTTP Request

### ISSUE THREAD

**Issue by emoran** [open-pay/openpay-js#6]
Hola estoy intentando consumir un servicio desde POSTMAN pero siempre recibo un error, donde debería o como debería colocar el parametro  de mi llave publica?

Este es mi request:

<img width="1366" alt="screen shot 2016-01-28 at 12 52 29 pm" src="https://cloud.githubusercontent.com/assets/1028534/12653605/48a6b66c-c5be-11e5-9f46-4b62a57c7118.png">

Gracias

**Comment by marcosAlvarado** [comment]
Buen día @emoran !
Hace falta que agregues la **Athorization**.

![screen shot 2016-01-28 at 12 09 20 pm](https://cloud.githubusercontent.com/assets/15144534/12654381/509ff518-c5b9-11e5-9361-df6bb9d07068.png)

-En la pestaña de **Athorization** debes seleccionar la opción **Basic Auth**.
-En el campo username debes ingresar tu **secret key**.

![screen shot 2016-01-28 at 12 02 13 pm](https://cloud.githubusercontent.com/assets/15144534/12654481/bd2c1144-c5b9-11e5-9718-a99c87695664.png)

Saludos cordiales!

**Comment by emoran** [comment]
Muchas gracias @marcosAlvarado funciona perfecto.

Lo que tengo que hacer para usarlo en cualquier sistema seria:

- Convertir la llave a base64 y agregar un espacio al final (emulando el password vacio)
- En mi Authorization header colocar Basic [el valor generado anteriormente]

Saludos!

**Comment by ecarloslr** [comment]
Hola @emoran, para el primer paso, primero le añades dos puntos a la llave y luego conviertes el resultado en base 64.

Es decir, el valor de Authorization sería:

`"Basic " + base64(privateKey + ":")`

La llave pública te sirve para registrar tokens, y sería la que usarías en la libreria de javascript. La privada te sirve para las demás operaciones como son cargos y listado de información, y esta solo la usarías en el back-end de tu sistema.

Saludos.
