### ISSUE TITLE
Convertir en módulo NPM

### ISSUE THREAD

**Issue by ghost** [open-pay/openpay-js#7]
En **npm** ya se tiene la biblioteca del servidor (**node**), por favor, incluyan ésta también en el registro para evitar el uso de _shims_ en webpack o browserify; nada será mejor que `npm install --save openpay-js`.

**Comment by oquis** [comment]
+1

**Comment by jmz7v** [comment]
A mi también me ayudaría mucho si openpay funcionara desde npm para webpack

**Comment by kiramishima** [comment]
si, estaria genial via npm o bower

**Comment by climaa** [comment]
+1

**Comment by rikantro** [comment]
+1

**Comment by kiramishima** [comment]
sigue sin tener soporte, parece que alguien ya hizo el PR desde el 2015

**Comment by canoqb10** [comment]
+1

**Comment by netkof** [comment]
+1

**Comment by rakirox** [comment]
+1

**Comment by alanleyva** [comment]
+1

**Comment by e-hop** [comment]
+1

**Comment by canotech** [comment]
+1

**Comment by EmmanuelSkapple** [comment]
es un dolor de cabeza integrarlo desde React js. ojala pronto lo hagan

**Comment by climaa** [comment]
Parece que no les importó... Apenas veo una acción despues de 4
¡Gracias!

**Comment by EmmanuelSkapple** [comment]
No no les importo, termine utilizando Coneckta mejor

**Comment by DarkUnknowKnigth** [comment]
Es necesario tener el paquete de npm esto para evitar tener que integrarlo por fuentes no confiables
