### ISSUE TITLE
TypeError: n[fieldName].push is not a function

### ISSUE THREAD

**Issue by Menusito** [open-pay/openpay-js#8]
OpenPay.token.extractFormAndCreate(
		$('#processCard'), 
		SuccessCallback, 
		ErrorCallback);

TypeError: n[fieldName].push is not a function

**Comment by mislas87** [comment]
Hola, ¿puedes darme más detalle de como generaste ese error?, esto para poder reproducirlo, asumo que tienes un html con las librerias requeridas y un html con un formulario que llena data-openpay-card de manera correcta, te recomiendo darle un vistazo a éste proyecto [https://github.com/open-pay/openpay-shopping-sample](https://github.com/open-pay/openpay-shopping-sample), es una sencilla implementación del uso de la librería.

Saludos y quedo en espera de tu respuesta.

**Comment by Menusito** [comment]
hoy monte un nuevo ejemplo en blanco y parece que ya no sucede el error. Me hizo dudar si fue una cuestión mía o si ya resolvieron el error. Como sea, parece que ya quedo resuelto.

**Comment by mislas87** [comment]
De acuerdo, saludos.

**Comment by angelscabrerag** [comment]
El Error TypeError: object[fieldName].push is not a function - openpay.v1.js:318:25  me aparece solo cuando utilizo los campos en el formulario:

data-openpay-card-address="line1"
data-openpay-card-address="line2"
data-openpay-card-address="city"
data-openpay-card-address="state"
data-openpay-card-address="country_code"
data-openpay-card-address="postal_code"

Al revisar la linea de codigo indicada (318) en https://openpay.s3.amazonaws.com/openpay.v1.js es: `object[fieldName].push(inputValue || '');`

el mismo error aparece al usar ambas versiones de la libreria (no min.js o min.js). Al retirar los campos data-openpay-card-address todo funciona correctamente.
